app: # 基本配置信息
  env: local # 环境
  port: 8081 # 服务监听端口
  app_name: online-exam # 应用名称
  app_url: http:localhost # 用于域名
  db_type: mysql # 使用的数据库

zap: # 日志配置
  level: info # 日志级别
  prefix: '[online_exam/server]' # 日志前缀
  format: console # 输出格式
  director: log # 日志存放的文件
  encode_level: LowercaseColorLevelEncoder # 编码级别
  stacktrace_key: stacktrace # 追踪栈名
  max_age: 0 # 日志留存时间
  show_line: true # 显示行
  log_in_console: true # 输出控制台

mysql: # MySQL 配置
  host: 127.0.0.1 # 服务器地址
  port: 3306 # MySQL 访问端口
  config: charset=utf8mb4&parseTime=True&loc=Local # 其他配置
  db_name: online_exam_db # 数据库名称
  username: root # 用户名
  password: 123456 # 密码
  prefix: "t_" # 全局表前缀，单独定义 TableName 不生效
  singular: false # 是否开启全局禁用复数，true 表示不开启
  engine: "" #  引擎，默认 InnoDB
  max_idle_conns: 10 # 最大空闲连接数
  max_open_conns: 100 # 最大连接数
  log_mode: error # 日志级别
  log_zap: false # 是否通过 zap 库写日志文件

pgsql: # PostgresSQL 配置
  host: localhost # 服务器地址
  port: 5432 # PostgresSQL 访问端口
  config: sslmode=disable TimeZone=Asia/Shanghai # 其他配置
  db_name: online_exam_db # 数据库名称
  username: postgres # 用户名
  password: 123456 # 密码
  prefix: "t_" # 全局表前缀，单独定义 TableName 不生效
  singular: false # 是否开启全局禁用复数，true 表示不开启
  engine: "" #  引擎，默认 InnoDB
  max_idle_conns: 10 # 最大空闲连接数
  max_open_conns: 100 # 最大连接数
  log_mode: error # 日志级别
  log_zap: false # 是否通过 zap 库写日志文件