definitions:
  request.CreateExaCustomerRequest:
    properties:
      customerName:
        description: 客户名
        type: string
      customerPhoneData:
        description: 客户手机号
        type: string
      sysUserAuthorityID:
        description: 管理角色ID
        type: integer
      sysUserID:
        description: 管理ID
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /customer/customer:
    post:
      consumes:
      - application/json
      parameters:
      - description: 客户用户名, 客户手机号码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.CreateExaCustomerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 创建客户
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      summary: 创建客户
      tags:
      - ExaCustomer
swagger: "2.0"
